apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: composer-user-workloads
  name: composer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
