scotia_project_dbt:
  outputs:
    dev:
      dataset: stocks
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: dbt_service_account.json
      location: US
      method: service-account
      priority: interactive
      project: bigquerysheets-404104
      threads: 2
      type: bigquery
  target: dev
